version: '3'
services:
  backend:
    image: sarang033/expense-backend
    container_name: backend
    ports:
      - "5001:5001"

  frontend:
    image: sarang033/expense-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend